### ISSUE TITLE
Null Exception - ClientNetworkStatus.cs

### ISSUE THREAD

**Issue by goetzcj** [ringcentral/ringcentral-csharp#17] opened 2016-01-18 23:17 UTC
After running a subscription for a long period of time, I am receiving a null exception that isn't handled in the `ParseCheckSocketConnectException<T>` method.  Specifically the line:

```
PubnubClientError error = new PubnubClientError(statusCode, PubnubErrorSeverity.
Warn, true, ex.Message, ex, PubnubMessageSource.Client, null, null, errorDescription,
string.Join(",", channels), string.Join(",", channelGroups));
```

The null exception is stating that "channels" cannot be null.  At that point the exception will stop the program execution.  Looking for a solution that would at a minimum throw a disconnect message back to be handled via the subscription implementation call back.

**Comment by grokify** [comment] 2016-02-12 19:28
Thanks for reporting this. We are working on resolving this and will provide an update when available.

**Comment by nrobison** [comment] 2016-03-28 21:45
I am unable to reproduce this even when running long subscriptions. Is there more information you can provide me? I have a hunch this has been related to the other issues but as I can't reproduce this error. #16 and #15  I was able to reproduce anywhere from 8-12hrs into a long running a subscription. After running a subscription for over 48hrs, with new fixes, I was not getting any errors including this one. 
The console app uses .NET 4.0 and sent a sms out every 15 minutes over those 48hrs. This included handling the notifications received as well.

**Comment by grokify** [comment] 2016-04-25 19:34
@goetzcj Since #15 and #16 have been resolved which may have been related to this and we haven't been able to reproduce this issue, I'm going to close this for now. If it comes up again, please post here.

**Closed** 2016-04-25 19:34 UTC
