### ISSUE TITLE
Error after application is idle for a long time 

### ISSUE THREAD

**Issue by eziel** [ringcentral/ringcentral-csharp#24] opened 2016-05-04 22:48 UTC
After my program is running for about 20 minutes the application crashes with the following error:
```
System.Exception: Access token corrupted
   at RingCentral.Subscription.SubscriptionServiceImplementation.Renew()
   at RingCentral.Subscription.SubscriptionServiceImplementation.OnTimedExpired(Object source)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

This is my code:
```
Dim subscription = New SubscriptionServiceImplementation With {._platform = ringCentral}
subscription.AddEvent("/restapi/v1.0/account/~/extension/~/presence?detailedTelephonyState=true")
Dim responsePub = subscription.Subscribe(AddressOf ActionOnUser, AddressOf ActionOnConnect, AddressOf ActionOnError) 
```

**Comment by grokify** [comment] 2016-05-04 22:51
Is this running against the production or sandbox endpoints?

* Production: `https://platform.ringcentral.com`
* Sandbox: `https://platform.devtest.ringcentral.com`

**Comment by eziel** [comment] 2016-05-04 22:51
Production

**Comment by tylerlong** [comment] 2016-05-05 11:22
@eziel 

I was unable to reproduce the same issue with the following code:

```csharp
using RingCentral.SDK;
using RingCentral.Subscription;
using System.Windows;
using System.Diagnostics;

namespace WpfApplication1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private SDK rcsdk;
        private Platform platform;
        private SubscriptionServiceImplementation ssi;

        public MainWindow()
        {
            InitializeComponent();
            rcsdk = new SDK(Config.Instance.AppKey, Config.Instance.AppSecret, Config.Instance.ServerUrl, "test app", "1.0");
            platform = rcsdk.GetPlatform();
            platform.Authorize(Config.Instance.Username, Config.Instance.Extension, Config.Instance.Password, true);
            ssi = new SubscriptionServiceImplementation { _platform = platform };
            ssi.AddEvent("/restapi/v1.0/account/~/extension/~/presence?detailedTelephonyState=true");
            ssi.Subscribe(UserCallback, ConnectCallback, ErrorCallback);
        }

        private void UserCallback(object obj)
        {
            Debug.WriteLine("UserCallback is called");
        }

        private void ConnectCallback(object obj)
        {
            Debug.WriteLine("ConnectCallback is called");
        }

        private void ErrorCallback(object obj)
        {
            Debug.WriteLine("ErrorCallback is called");
        }
    }
}
```

I will keep it running all night and check its status tomorrow morning.

**Comment by eziel** [comment] 2016-05-05 18:13
Did it run all night without an error?

**Comment by eziel** [comment] 2016-05-05 19:28
Today the UserCallback stopped firing on presence changes. [the connect event does fire and says "Connected".

I didn't change any code since yesterday, not sure why it won't work anymore.

**Comment by tylerlong** [comment] 2016-05-06 00:18
I checked it this morning and there was error. The error is reported and investigated here: https://github.com/ringcentral/ringcentral-csharp/issues/25

So it failed due to a separate issue. I will continue to do testing.

**Comment by tylerlong** [comment] 2016-05-06 01:13
Update:

I fixed #25 and started the testing again. It has been running for 1 hour or so and there is no more errors.

By the way, `Access token corrupted` has several causes:

- Different token types, e.g. using refresh token for getting access to API
- Access token is inactive (refreshed with new one, evicted from grid by expiration, revoked by client)

More investigation is needed. If you can reproduce the issue constantly, please advise me the steps.

**Comment by eziel** [comment] 2016-05-06 03:47
Yes I could duplicate the issue at any time.. so far I only tried it with the debugger on and stopping it in the middle. will try it without debugger too.

Bigger problem now is that the presence is  no longer firing making the app completely useless.

**Comment by tylerlong** [comment] 2016-05-06 05:48
The testing app has been running for 4 hours and there is still no error.

> Today the UserCallback stopped firing on presence changes. [the connect event does fire and says "Connected".

Please do turn off the debugger. I encountered something weird with the debugger on yesterday. Sometimes the debugger could cause the whole app hung. Everything was alright after I removed all of the breakpoints.

**Comment by eziel** [comment] 2016-05-08 17:04
Hello just tried without any breakpoints.. same problem!
`System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>/LM/W3SVC/9/ROOT-1-131071986972319138</AppDomain><Exception><ExceptionType>System.Exception, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Access token corrupted</Message><StackTrace>   at RingCentral.Subscription.SubscriptionServiceImplementation.Renew()
   at RingCentral.Subscription.SubscriptionServiceImplementation.OnTimedExpired(Object source)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()</StackTrace><ExceptionString>System.Exception: Access token corrupted
   at RingCentral.Subscription.SubscriptionServiceImplementation.Renew()
   at RingCentral.Subscription.SubscriptionServiceImplementation.OnTimedExpired(Object source)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()</ExceptionString></Exception></TraceRecord>
`

**Comment by tylerlong** [comment] 2016-05-09 05:21
I would like to help but I was unable to reproduce the issue. Can you reproduce the issue in sandbox environment? If so, do you mind sharing your credentials with me?  Do you mind posting your source code here(or send to me by email)?

**Comment by eziel** [comment] 2016-05-09 17:34
When using sandbox I have no issue. only in production. here's the full code. 

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RingCentral.SDK;
using RingCentral.Subscription;

namespace testRingCentral
{
    class Program
    {
        Platform ringCentral;
        SubscriptionServiceImplementation Subscription;

        static void Main(string[] args)
        {
            Program rc = new Program();
            rc.ConnectRingcentral();
        }
        
       void ConnectRingcentral()
        {
            ringCentral = new SDK("removed", "removed", "https://platform.ringcentral.com", "Freshdesk", "1.0").GetPlatform();
            ringCentral.Authorize("phoneNumber", "ext", "password", true);

            Subscription = new SubscriptionServiceImplementation();
            Subscription._platform = ringCentral;
            Subscription.AddEvent("/restapi/v1.0/account/~/extension/~/presence?detailedTelephonyState=true");
            Subscription.Subscribe(UserCallback, ConnectCallback, ErrorCallback);
            Console.ReadKey();
       }

        void UserCallback(object obj)
        {
            Console.WriteLine(obj.ToString());
        }

        void ConnectCallback(object obj)
        {
            Console.WriteLine(obj.ToString());
        }

        void ErrorCallback(object obj)
        {
            Console.WriteLine(obj.ToString());
        }
    }
}
`

**Comment by eziel** [comment] 2016-05-09 19:51
I tried now to let the program run without any activity on the phone, it still crashed after about an half hour, but the error message is different: 
`
Additional information: Resource for parameter [subscriptionId] is not found`

**Comment by tylerlong** [comment] 2016-05-10 00:46
@eziel the last issue you reported is elaborated here: https://github.com/ringcentral/ringcentral-csharp/issues/25

We confirmed it as a bug and we will fix it ASAP. If you are OK with compiling the code yourself, you can fix it by increasing the value of `RenewHandicap`, just like described in https://github.com/ringcentral/ringcentral-csharp/issues/25

For the production-only issue, I really have no idea. I will ask my colleague for help.

@kirill-konshin @grokify what do you think? The issue is only reproduced in production.

**Comment by grokify** [comment] 2016-05-10 01:23
@eziel If this is only in production and not sandbox, this appears to be an API issue and not a SDK issue.

To resolve API issues, we should have our Developer Relations Engineering team engaged via the [Developer Community](https://devcommunity.ringcentral.com) or a [support case](https://developer.ringcentral.com/support.html). I'll direct our DevRel team to [the thread you already created](https://devcommunity.ringcentral.com/ringcentraldev/topics/error-after-application-is-idle-for-a-long-time) where I'll post an update. You can also create a support case via the link above.

Also, since this appears to be an API issue, we will close this SDK issue for now.

**Closed by grokify** 2016-05-10 01:23 UTC

**Comment by tylerlong** [comment] 2016-05-10 04:43
@grokify  I just checked. Actually I was testing against production since the very beginning of this issue. I couldn't reproduce the `Access token corrupted` issue. So this seems a specific issue only for @eziel 's production environment.
