### ISSUE TITLE
Exception not being handled - SubscriptionServiceImplementation.cs

### ISSUE THREAD

**Issue by goetzcj** [ringcentral/ringcentral-csharp#16] opened 2016-01-18 23:09 UTC
In the `RingCentral.NET40` SDK, when running subscriptions for long periods of time, I am getting an exception thrown that isn't handled anywhere in the `Renew()` method.  Everything will run great for several hours and then an exception will be thrown from:

```
Response response = _platform.Put(request);
```

The exception says that the `subscriptionId` is null when it catches the exception.  Checking the code prior to the put request shows that the `subscriptionId` is not null.  At that point the program will stop execution.

In the catch for the `Renew()` method, the first thing it does is to `Unsubscribe()`.  This throws a disconnect message which I can handle via the call back message and attempt to create a new subscription. For the moment, I have commented out the throw line and have the catch returning null then deal with the disconnect message by recreating the subscription.

**Comment by grokify** [comment] 2016-02-12 19:29
Thanks for reporting this. We are working on resolving this and will provide an update when available.

**Comment by nrobison** [comment] 2016-03-28 18:29
After digging into this it turns out the property `private const int RenewHandicap = 60;` was not allowing   enough time for the timer to execute the renew of the subscription after a long period of time.  The renew handicap has been correctly adjusted to `private const int RenewHandicap = 1000;`  I have run a console app for over 48hrs using this and did not have that error reproduce. 

The subscriptionId being null was a result of the renew subscription no getting the correct response (trying to renew after it expired).  These changes are currently available in the prerelease version on nuget as well as the develop branch.

**Comment by goetzcj** [comment] 2016-04-03 15:03
I don't see the errors that were popping up before but now it seems that the subscription actions are not returning any results.  For example, I am subscribing to the "/restapi/v1.0/account/~/extension/~/presence?detailedTelephonyState=true" to capture the ringing event.  In the present state, the ActionOnMessage event doesn't fire at all when I am testing by dialing in and debugging the code at the same time.

**Comment by nrobison** [comment] 2016-04-04 06:17
@goetzcj  That is great to hear. Please update to the latest pre-release to resolve the newest issue of not firing the action. There was an issue decrypting messages from switching to PubNub PCL which was causing the action to fail to fire. Please let me know if that resolves the issue. Messages are now being decrypted and allowing the `ActionOnMessage` to fire.

**Comment by goetzcj** [comment] 2016-04-06 18:45
@nrobison Looks like the initial testing with alpha 7 is positive.  We will continue to test for another day or so but so far so good.

**Comment by grokify** [comment] 2016-04-11 23:06
@goetzcj How does everything look?

**Comment by grokify** [comment] 2016-04-25 19:30
@goetzcj I'm going to close this out now. Please post here if this issue resurfaces.

**Closed by grokify** 2016-04-25 19:30 UTC
