### ISSUE TITLE
Receiving warnings on NuGet install in Xamarin

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-csharp#18] opened 2016-02-23 20:56 UTC
Receiving the following warnings while installing via NuGet in Xamarin C# Project.

```
WARNING: RingCentralSDK Package contains PowerShell scripts which will not be run.
The Microsoft.Bcl.Build package has a license agreement which is available at http://go.microsoft.com/fwlink/?LinkId=329770
Please review this license agreement and remove the package if you do not accept the agreement.
Check the package for additional dependencies which may also have license agreements.
Using this package and any dependencies constitutes your acceptance of these license agreements.
The Microsoft.Bcl package has a license agreement which is available at http://go.microsoft.com/fwlink/?LinkId=329770
Please review this license agreement and remove the package if you do not accept the agreement.
Check the package for additional dependencies which may also have license agreements.
Using this package and any dependencies constitutes your acceptance of these license agreements.
The Microsoft.Net.Http package has a license agreement which is available at http://go.microsoft.com/fwlink/?LinkId=329770
Please review this license agreement and remove the package if you do not accept the agreement.
Check the package for additional dependencies which may also have license agreements.
Using this package and any dependencies constitutes your acceptance of these license agreements.
```

**Comment by tylerlong** [comment] 2016-05-04 08:44
Tested with version 0.1.21. I cannot reproduce the issue:

```
Adding RingCentralSDK...
Attempting to resolve dependency 'Newtonsoft.Json (≥ 7.0.1)'.
Downloading RingCentralSDK 0.1.21...
Attempting to resolve dependency 'PubnubPCL (≥ 3.7.0.1)'.
Attempting to resolve dependency 'Portable.BouncyCastle-Signed (≥ 1.7.0.2)'.
Attempting to resolve dependency 'PCLCrypto (≥ 1.0.86)'.
Attempting to resolve dependency 'Validation (≥ 2.2.8)'.
Attempting to resolve dependency 'PInvoke.NCrypt (≥ 0.3.2)'.
Attempting to resolve dependency 'PInvoke.Windows.Core (≥ 0.3.2)'.
Attempting to resolve dependency 'PInvoke.BCrypt (≥ 0.3.2)'.
Attempting to resolve dependency 'PInvoke.Kernel32 (≥ 0.3.2)'.
Installing 'RingCentralSDK 0.1.21'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/portable-net45+sl5+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/portable-net40'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/net40'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/net45'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/sl5'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/MonoTouch1'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/MonoAndroid1'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/MonoMac'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/Xamarin.Mac'.
Added file 'RingCentral.dll' to folder 'RingCentralSDK.0.1.21/lib/Xamarin.iOS'.
Added file 'RingCentralSDK.0.1.21.nupkg' to folder 'RingCentralSDK.0.1.21'.
Successfully installed 'RingCentralSDK 0.1.21'.
Removing 'RingCentralSDK 0.1.2-alpha7' from MyTestApp.
Removed reference 'RingCentral' from project 'MyTestApp'.
Added file 'packages.config'.
Added file 'packages.config' to project 'MyTestApp'.
Successfully removed 'RingCentralSDK 0.1.2-alpha7' from MyTestApp.
Adding 'RingCentralSDK 0.1.21' to MyTestApp.
For adding package 'RingCentralSDK 0.1.21' to project 'MyTestApp' that targets 'xamarinios10',
>> Assembly references are being added from 'lib/Xamarin.iOS'
Added reference 'RingCentral' to project 'MyTestApp'.
Added file 'packages.config'.
Added file 'packages.config' to project 'MyTestApp'.
Successfully added 'RingCentralSDK 0.1.21' to MyTestApp.
Uninstalling 'RingCentralSDK 0.1.2-alpha7'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/portable-net45+sl5+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/portable-net45+sl5+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/portable-net40'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/portable-net40'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/MonoAndroid1'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/MonoAndroid1'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/Xamarin.Mac'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/Xamarin.Mac'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/Xamarin.iOS'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/Xamarin.iOS'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/MonoTouch1'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/MonoTouch1'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/MonoMac'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/MonoMac'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/net40'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/net40'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/net45'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/net45'.
Removed file 'RingCentral.dll' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/sl5'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib/sl5'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7/lib'.
Removed file 'RingCentralSDK.0.1.2-alpha7.nupkg' to folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7'.
Removed folder '/Users/tyler.liu/Projects/MyTestApp/packages/RingCentralSDK.0.1.2-alpha7'.
Successfully uninstalled 'RingCentralSDK 0.1.2-alpha7'.


RingCentralSDK successfully added.

```

Let's close this issue if you cannot reproduce the issue either. @bdeanindy

**Comment by tylerlong** [comment] 2016-05-04 08:58
> `RingCentralSDK Package contains PowerShell scripts which will not be run.`

I think this issue is OK because PowerShell is for Windows only. I assume you are running Xamarin Studio on Mac.

For the license issues, I cannot reproduce it with iOS C# project. I can reproduce it with a C# Console project:

![screen shot 2016-05-04 at 4 53 14 pm](https://cloud.githubusercontent.com/assets/733544/15009405/c02fb69c-1218-11e6-9cd7-68a7eb24414f.png)

I agreed to the license terms and there was no more warnings.

**Comment by grokify** [comment] 2016-05-10 01:31
This looks like a normal part of accepting different licenses. Closing for now.

Please comment if this is preventing you from using this SDK and we can revisit.

**Closed by grokify** 2016-05-10 01:31 UTC
